server:
  port: 8080

spring:
  application:
    name: aichat-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aichat?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: aichat_app
    password: Lxt962464
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

zhipu:
  api-key: 62ea9af647694683a587969105f81778.Yz47X6dk2EXnUEca

server.servlet.encoding:
    charset: UTF-8
    enabled: true
    force: true